ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/sar
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation/sar/a96t356/
obj-y     :=  abov_sar.o
