#=============================================================================
#  wifi
#=============================================================================
obj-$(CONFIG_WIFI_DELAY_STATISTIC) += ipv4/wifi_delayst.o
obj-$(CONFIG_HW_WIFI) += ipv4/
obj-$(CONFIG_HW_BOOSTER) += booster/
obj-$(CONFIG_CHR_NETLINK_MODULE) += chr/
obj-$(CONFIG_HW_DPIMARK_MODULE) += hw_dpi_mark/
EXTRA_CFLAGS += -Idriver/huawei_platform
