# audio drivers
subdir-ccflags-y += -Idrivers/devkit/audiokit/smartpakit/
obj-$(CONFIG_CS35L41) += cs35l41/
obj-$(CONFIG_TAS2557) += tas2557/
obj-$(CONFIG_TFA9894) += tfa9894/
obj-$(CONFIG_HEADSET_AUTO_CALIB) += hs_auto_calib/