ccflags-y += -Idrivers/huawei_platform/audio/tfa9894/inc
ccflags-y += -Idrivers/devkit/audiokit/
tfa9894-objs := tfa98xx.o tfa_container.o tfa_debug.o tfa_dsp.o tfa_init.o
obj-$(CONFIG_TFA9894) += tfa9894.o
